---
type: showroom

default_width: 30
persist_url_state: true

view_switcher:
  enabled: true
  default_mode: split

tabs:
- name: Red Hat Cloud Extensions Console
  url: 'https://osac-ui-osac.${DOMAIN}'
- name: OpenShift Console
  url: 'https://console-openshift-console.${DOMAIN}'
- name: Keycloak
  url: 'https://keycloak-keycloak.${DOMAIN}'
- name: Terminal
  path: /wetty
  port: 443
