= Red Hat Cloud Extensions Credentials

This page summarizes all credentials that you need in this workshop as a reference. You will also find these credentials in the instructions at the point where you need them.

== Red Hat Cloud Extensions UI

* *Red Hat Cloud Extensions UI*: {osac_ui_url}^. You do not need to follow this link - use the tab on the right. Use the credentials below to log into the Red Hat Cloud Extensions UI.
* *Red Hat Cloud Extensions admin credentials*:
+
.*Admin user*
[role=copy,subs=attributes]
----
{osac_admin_user}
----
+
.*Admin user password*
[role=copy,subs=attributes]
----
{osac_admin_password}
----

== Keycloak

You do not need to log into Keycloak for this workshop, but you can explore the Keycloak admin console if you wish.

* *Keycloak UI*: {osac_keycloak_url}^
* *Keycloak admin credentials*:
+
.*Admin user*
[source,role=copy,subs=attributes]
----
{osac_keycloak_admin_user}
----
+
.*Admin user password*
[source,role=copy,subs=attributes]
----
{osac_keycloak_admin_password}
----

== OpenShift Container Platform

You can explore the OpenShift cluster and Red Hat Cloud Extensions components through the OpenShift Console.

* *OpenShift Console*: {openshift_console_url}^. You do not need to follow this link - use the tab on the right. 
* *OpenShift API URL*: {openshift_api_url}

* *OpenShift cluster admin credentials*:
+
.*Cluster admin user*
[source,role=copy,subs=attributes]
----
{openshift_cluster_admin_username}
----
+
.*Cluster admin user password*
[source,role=copy,subs=attributes]
----
{openshift_cluster_admin_password}
----

== OpenShift Container Platform CLI

* Switch to the *Terminal* tab and log into Red Hat OpenShift Container Platform from the command line:
+
[source,role=execute,subs=attributes]
----
oc login --insecure-skip-tls-verify \
  --username {openshift_cluster_admin_username} \
  --password {openshift_cluster_admin_password} \
  {openshift_api_url}
----

== Red Hat Cloud Extensions CLI

* Switch to the *Terminal* tab and log into Red Hat Cloud Extensions from the command line:
+
[source,role=execute,subs=attributes]
----
osac login --insecure \
  --issuer="https://keycloak-keycloak.{openshift_cluster_ingress_domain}/realms/osac" \
  --flow=password \
  --user={osac_admin_user} \
  --password={osac_admin_password} \
  https://fulfillment-internal-api-osac.{openshift_cluster_ingress_domain}
----
